SELECT * FROM PDS;

DROP TABLE PDS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_PDS;


CREATE TABLE PDS(
   SEQ NUMBER(8) PRIMARY KEY,
   ID VARCHAR2(50) NOT NULL,
   TITLE VARCHAR2(200) NOT NULL,
   CONTENT VARCHAR2(4000) NOT NULL,
   FILENAME VARCHAR2(50) NOT NULL,
   NEWFILENAME VARCHAR2(50) NOT NULL,
   READCOUNT NUMBER(8) NOT NULL,
   DOWNCOUNT NUMBER(8) NOT NULL,
   REGDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_PDS
START WITH 1
INCREMENT BY 1;

ALTER TABLE PDS
ADD CONSTRAINT FK_PDS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);


SELECT *
FROM PDS;


SELECT ORIGINALFILENAME
FROM PDS
WHERE FILENAME = '1616396350300.txt';


UPDATE PDS
SET READCOUNT = READCOUNT + 1
WHERE SEQ = 4;


SELECT SEQ, ID, TITLE, CONTENT, ORIGINALFILENAME,
FILENAME, READCOUNT, DOWNCOUNT, REGDATE 
FROM PDS 
WHERE SEQ = 4;


UPDATE PDS
SET TITLE = 123, CONTENT = 213, ORIGINALFILENAME = 213, FILENAME = 213
WHERE SEQ = 2;


SELECT RNUM, SEQ, ID, TITLE, CONTENT, ORIGINALFILENAME,
FILENAME, READCOUNT, DOWNCOUNT, REGDATE
FROM
(SELECT ROW_NUMBER()OVER(ORDER BY SEQ DESC) AS RNUM,
SEQ, ID, TITLE, CONTENT, ORIGINALFILENAME, FILENAME, READCOUNT, DOWNCOUNT, REGDATE
FROM PDS
ORDER BY SEQ DESC)
WHERE RNUM >= 1 AND RNUM <= 10;



commit;


